### PR TITLE
Add Docker-based CI to build CIAs

### PR DESCRIPTION
**Pull request by RoblKyogre**
Alternate to #13

(do prefer this pr personally)

**Description**
Adds a GitHub Actions workflow to automatically build a CIA upon commits to n3ds-main
Also fixes a perms issue on the scripts that prevents the Dockerfile from being built
Also updates the dockerfile to download a fork of bannertool
And also changes the dockerfile to use an image that already has devkitArm set up

**Purpose**
Would be useful for releasing nightly builds of this app without having to compile it yourself. Could also be integrated into Universal Updater by having it create a "nightly" release in GitHub Releases, tho that isn't currently implemented in this PR.

### CODE REVIEW

**Comment by RoblKyogre** [comment]
Closing, seems like devkitpro [blocks CI from using dkp-pacman](https://github.com/devkitPro/pacman/issues/31#issuecomment-1081541168)

**Comment by RoblKyogre** [comment]
actually, just realized that this doesn't necessarily have to be closed yet...
could change the dockerfile to be based on dkp's container instead

**Comment by RoblKyogre** [comment]
gahhh, mucked this branch up when trying to merge into another branch on my own end, have to close this...

**Comment by RoblKyogre** [comment]
accidentally merged another branch into this one, reverted the merge commit that did it (was worried it would fuck things up which is why i closed the pr before figuring out how to revert it)

**Comment by zoeyjodon** [comment]
Awesome! I've wanted to add this for a while, but kept putting it off. LGTM!

**Pull request merged**
